import {Annotation} from "@langchain/langgraph"
import { BaseMessage } from "@langchain/core/messages"

//Structure for tracking completed tasks
export interface CompletedTask {
    agentName:string,
    taskDescription:string,
    output:string
}

export const ZyraState = Annotation.Root({
    //Multi-turn chat message history
    messages:Annotation<BaseMessage[]>({
        reducer:(curr,update)=>curr.concat(update),
        default:()=>[],
    }),

    //The step by step plan generated by the planner
    plan:Annotation<string[]>({
        reducer:(_,update)=>update,
        default:()=>[],
    }),

    //Log outputs from workers that have finished
    completedTasks:Annotation<CompletedTask[]>({
        reducer:(curr,update)=>curr.concat(update),
        default:()=>[],
    }),

    //the next destination decided by the delegation manager
    nextDestination:Annotation<string>({
        reducer:(_,update)=>update,
        default:()=>"Planner",
    }),

    //specefic task assigned to the next worker
    currentTask:Annotation<string>({
        reducer:(_,update)=>update,
        default:()=>"",
    }),

    userId: Annotation<string>({
    reducer: (_, update) => update,
    default: () => "user-1",
  }),

    //the completed final response for the user
    finalResponse:Annotation<string>({
        reducer:(_,update)=>update,
        default:()=>"",
    })
});

