export const injection_token = {
  DB_CONNECTION: 'POSTGRESQL_INJECTION',
  REDIS_CONNECTION: 'REDIS_INJECTION',
  CLOUDINARY_CONNECTION: 'CLOUDINARY_INJECTION',
  NODEMAILER_CONNECTION:'NODEMAILER_INJECTION',
  RMQ_CONNECTION: 'RMQ_INJECTION',
};
